# Generated by Django 5.0.6 on 2024-07-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todolist", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TodoModelCreate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("add", models.CharField(max_length=20)),
            ],
        ),
    ]
